name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : Login Credi
      env:
        DOCKER_USER: ${{ secrets.USER_NAME }}   
        DOCKER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    - name: Login
      run : docker login -u $USER_NAME -p $USER_PASSWORD
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 'demoimage'
   
    - name: Push Image
      run : docker push demoimage
